### ISSUE TITLE
Highlight metrics in search results

### ISSUE THREAD

**Issue by alexmunk** [dashbase/dashbase-engine-web#331] opened 2017-01-22 07:44 UTC
I searched the demo instance for:

bytesSent: 5633.0 AND host: 79.28.131.251 

Returns properly, but 5633 isn't highlighted.

**Comment by khou** [comment] 2017-01-23 00:10
@javasoze
This is not an issue with conjuction, but seems like an issue only for `bytesSent`.
All other fields highlight by inserting a span tag with class `hl` in the response, but query on `bytesSent` does not do so. Adding of the span tag occurs in the backend

**Comment by javasoze** [comment] 2017-01-23 05:12
the issue is bytesSent is a numeric value, not text. So highlighting does not apply.

I will take this an think about it...

**Comment by javasoze** [comment] 2017-01-25 07:26
This is actually not bad to fix but it needs to be done in the engine, will create a ticket there.

**Comment by javasoze** [comment] 2017-01-25 07:27
Tracked under: https://github.com/dashbase/dashbase-engine/issues/416

Closing this one.

**Closed by javasoze** 2017-01-25 07:27 UTC
